# Generated by Django 4.0.2 on 2022-02-26 21:42

from django.db import migrations, models

def create_data(apps, schema_editor):
    JournalEntries = apps.get_model('students', 'Student')
    JournalEntries(entry_id=420, title="Initial DB Title", description="Initial DB Description").save()

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Todo',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('title', models.CharField(max_length=120)),
        #         ('description', models.TextField()),
        #         ('completed', models.BooleanField(default=False)),
        #     ],
        # ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('reminderType', models.CharField(max_length=120)),
                ('date', models.DateTimeField()),
                ('repeating', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
