# Generated by Django 4.0.2 on 2022-02-26 21:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def create_data(apps, schema_editor):
    JournalEntries = apps.get_model('students', 'Student')
    JournalEntries(entry_id=420, title="Initial DB Title", description="Initial DB Description").save()
class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(default='')),
                ('completed', models.BooleanField(default=False)),
                ('reminderType', models.CharField(choices=[('M', 'Medicine'), ('A', 'Appointment'), ('O', 'Other')], max_length=1)),
                ('repeating', models.CharField(choices=[('D', 'Daily'), ('W', 'Weekly'), ('O', 'Other')], max_length=1)),
                ('date', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GameHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField()),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('player', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
