# Generated by Django 4.0.3 on 2022-04-04 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reminder",
            name="reminderType",
            field=models.CharField(
                choices=[("M", "Medicine"), ("A", "Appointment"), ("O", "Other")],
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="reminder",
            name="repeating",
            field=models.CharField(
                choices=[("D", "Daily"), ("W", "Weekly"), ("O", "Other")], max_length=1
            ),
        ),
    ]
