# Generated by Django 4.0.3 on 2022-04-06 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_id', models.IntegerField()),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.CharField(max_length=300, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='description',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='id',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='title',
        ),
        migrations.AlterField(
            model_name='reminder',
            name='reminderType',
            field=models.CharField(choices=[('M', 'Medicine'), ('A', 'Appointment'), ('O', 'Other')], max_length=1),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='repeating',
            field=models.CharField(choices=[('D', 'Daily'), ('W', 'Weekly'), ('O', 'Other')], max_length=1),
        ),
        migrations.AddField(
            model_name='reminder',
            name='todo_ptr',
            field=models.OneToOneField(auto_created=True, default='0', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='todo.todo'),
            preserve_default=False,
        ),
    ]
