# Generated by Django 4.0.2 on 2022-04-07 20:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_gamehistory_player_alter_gamehistory_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamehistory',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
