# Generated by Django 4.0.2 on 2022-04-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_gamehistory_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamehistory',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
