# Generated by Django 4.0.3 on 2022-04-06 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JournalEntry',
        ),
    ]
