# Generated by Django 4.0.3 on 2022-04-06 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_delete_journalentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntries',
            fields=[
                ('todo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='todo.todo')),
                ('entry_id', models.IntegerField()),
            ],
            bases=('todo.todo',),
        ),
    ]
