# Generated by Django 4.0.2 on 2022-04-07 20:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_gamehistory_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamehistory',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
