# Generated by Django 4.0.2 on 2022-04-07 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_gamehistory_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamehistory',
            old_name='time',
            new_name='date',
        ),
    ]
